# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-19 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoNinjas', '0002_dojos_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojos',
            name='desc',
            field=models.TextField(),
        ),
    ]
